- controllers/authController.js
refactored and fixed internal server error in the forgot password endpoint
> refactored and fixed internal server error

- controllers/adminControllers.js
- docs/API Endpoints Docs.md
- routes/updateUser.js
This PR adds an endpoint that allows users with admin privileges to retrieve a list of all users in the system as requested by the dashboard team. 
Link to issue: https://linear.app/zuri-project-backend/issue/AUT-32/za-030
Endpoint: GET https://auth.akuya.tech/api/users/ 
**Request:**
Header: -` Authorization (string)`: A valid JWT token with a "Bearer" prefix. 
Response:  
(HTTP Status Code: 200 OK) - Body: 
```
{
"success": true,
"data": {
"count": {
"admin": 2,
"registered_users": 54,
"total": 56
},
"users": [
{
"id": "1972d345-44fb-4c9a-a9e3-d286df2510ae",
"username": "test",
"first_name": "john",
"last_name": "doe",
"email": "pespadaspu@gufum.com",
"section_order": null,
"password": "$2b$10$NsWOprLVHjwb8miEfP.fQ.RWcvwJnlNoXyBtit6fpCZ9yr7KiA0em",
"provider": null,
"profile_pic": null, …
```
> add getAllUsers endpoint

- controllers/userController.js
- routes/auth.js
Related Issue:
https://linear.app/zuri-project-backend/issue/AUT-31/za-029
> Implement endpoint to change user email

- controllers/AuthenticationController/verifyUser.js
- controllers/AuthorizationController/authorize.js
- controllers/MessagingController/sendSignUpEmail.js
Previously the verification link sent to the user after signing up hit the server first, verified the link and redirected to the front end.
After deliberations between the frontend and the backend, we decided to send the link to the frontend first, and then the frontend sends a request to the server and receive a response.
This PR addresses that.
> revise signup flow.

- index.js
Switched the routes to use /api/auth.
> chore: cleanup routes

- controllers/AuthenticationController/enable2fa.js
- controllers/AuthenticationController/index.js
- controllers/AuthenticationController/send2faCode.js
- controllers/AuthenticationController/verify2fa.js
- routes/auth.js
- routes/authenticationRoute.js
This PR implements the 2FA flow feature.
`/2fa/enable` to enable 2FA for a user.
`/2fa/send-code` to send 2FA code to user.
`/2fa/verify-code` to verify 2FA code
> enable 2fa flow

- .github/PULL_REQUEST_TEMPLATE.md
- index.js
Added pull request template
Confirmed cors setup now works
> feat: new cors setup and pull request template added

- .github/workflows/staging.yml
- index.js
- middleware/logger.js
- package.json
- pnpm-lock.yaml
​
​
Added auto deployment using GitHub Actions
​
​
​
​
​
> ci: add autodeploy

- swagger_output.json
​
swagger documentation update
​
https://linear.app/zuri-project-backend/issue/AUT-18/za-018
​
updating the swagger documentation with the current endpoints deployed and running ok
​
tested locally using the staging url as base url for requests and it worked perfectly
​
- [ x] New feature (non-breaking change which adds functionality)
​
- [ x] My code follows the code style of this project.
- [ x] I have updated the documentation accordingly.
- [ x] I have read the **CONTRIBUTING** document.
> documentation file updated with all working endpoints

- controllers/AuthenticationController/authFacebook.js
- controllers/AuthenticationController/authGithub.js
- controllers/AuthenticationController/authGoogle.js
- controllers/AuthenticationController/index.js
- controllers/AuthenticationController/login.js
- controllers/AuthenticationController/revalidateLogin.js
- controllers/authFacebook.js
- controllers/gauthControllers.js
- controllers/githubauthController.js
- middleware/authGithub.js
- routes/auth.js
- routes/authenticationRoute.js
- validators/AuthenticationValidator/login.js
#Feat: Oauth Logins and Fix
​
​Added the Oauth login features and fixed verify token 
https://linear.app/zuri-project-backend/issue/AUT-3/za-003​
To implement login with socials
​
​
​
​
> Feat: Oauth logins and fix

- controllers/AuthenticationController/login.js
- controllers/AuthenticationController/verify2fa copy.js
This change checks if the user has the 2fa code auth enabled and automatically send the 2fa code while the user is been redirected to the confimation page.
​
​
​
​
​
​
​
> login checks if the user has 2fa enabled and send 2fa code to user mail

- .github/workflows/staging.yml
> ci: no testing the app since no env set up on github

- .github/workflows/staging.yml
> ci: no need to run the app

- controllers/AuthenticationController/createGuest.js
- controllers/AuthenticationController/index.js
- routes/authenticationRoute.js
In line with allowing guest checkout permssions, I implemented a guest user signup on the database to return a token for checkout in the response body.​
​NIL
​Guest users are to be allowed the permission for buying product on the website by registering the user and returning a token for verification and so this PR aims at solving this issue. 
​The endpoint was tested locally using Postman. The endpoint can be accessed using:
- POST /signup-guest
​
​
> Feat: Guest signup route

- controllers/AuthenticationController/verifyUser.js
- controllers/MessagingController/sendWelcomeMail.js
- middleware/authGithub.js
- services/passportService.js
​
The sendWelcomeEmail helper function is used to send the welcome email when a user verify
and when they signup with  any of the oauth services
The function requires the follow env variables to be set:
- AUTH_FRONTEND_DASHBOARD_URL
- EMAIL_SERVICE_WELCOME_URL
​
​
​
Tested with postman via the signup flow
​
​
​
> send welcome mail implementation

- controllers/PasswordController/change.js
- controllers/PasswordController/index.js
- routes/passwordRoute.js
- validators/PasswordValidator/changePassword.js
- validators/PasswordValidator/index.js
This feature implements the change user password for an already logged in user
​
​Nil
​In the event that a logged in user wants to change their password. This PR aims at solving this issue.
​The code was tested locally using Postman. The endpoint can be accessed using:
- POST /reset-password/change
​
​
> Feat: Change Password

- controllers/AuthenticationController/verify2fa copy.js
- controllers/MessagingController/resendVerificationEmail.js
- controllers/MessagingController/sendPasswordResetEmail.js
- controllers/MessagingController/sendSignUpEmail.js
​
​i updated all jwt tokens sent to emails to expire at 10mins and updated the response of 2fa login to match our login response
​
this change is required to stop user from being able to reverify using the same link after the speculated time
​
i tested it locally and it works fine​
​
​
> jwt expiration time set

- controllers/AuthenticationController/verify2fa.js
​
​i updated the 2fa response to include the token
2fa response when trying to login
​
To help improve the response gotten from the back end
​
Tested locally and working
​
​
​
> updated the 2fa code response

- typescript/controllers/MessagingController/index.ts
> Messaging controller converted to Typescript 

- typescript/middlewares/auth.ts
- typescript/middlewares/error.ts
- typescript/package.json
Authentication and Error handling middleware added
​
​
​
​
​
​
​
> feat: added auth and error handling middlewares

- controllers/AuthenticationController/logginResponse.js
- middleware/loginResponse.js
- models/Users.js
​
​To enhance data on app usage, we've added a last_login field in the user table and User model. This will help in the tracking of active users.
​
> Last Login Implementation

- typescript/@types/index.ts
- typescript/middlewares/error.ts
Interfaces for the models​
​
​
​
​
​
​
> feat: added the interface for the models

- swagger_output.json
​
updated the swagger documentation with the newly added routes and features
​
Documentation
​
To show the features and routes included in the API
​
i tested it locally and it worked fine
​
​
​
> swagger documentation updated

- swagger_output.json
​
​i fixed a data type error in the swagger docs
swagger documentation
​
To allow users input the proper data type
​
​Tested locally and working fine
​
​
> bug fixed in the swagger docs

- controllers/AuthenticationController/disable2fa.js
​
​The disable 2FA endpoint wasn't actually disabling 2FA for the user.
​
​
​
​
​
> disable 2fa

- controllers/AuthorizationController/authorize.js
​
modified the authorized endpoint
​
authorize
​
To optimize the authorization response
​
tested locally and fine
​
​
​
> authorized endpoint modified

- typescript/@types/index.ts
- typescript/config/db.config.ts
- typescript/controllers/UserController/index.ts
- typescript/controllers/UserController/messaging.ts
- typescript/controllers/UserController/validation.ts
- typescript/index.ts
- typescript/middlewares/error.ts
- typescript/package.json
- typescript/routes/userRouter.ts
- typescript/services/UserService/IUserService.ts
- typescript/services/UserService/index.ts
- typescript/utils/index.ts
Refactored the authentication controllers and service
​
​
​
​
​
​
​
> Authentication refactored

- controllers/AuthenticationController/changeEmail.js
- controllers/AuthenticationController/index.js
- routes/auth.js
- routes/authenticationRoute.js
​
I have fixed the issues with the change-email endpoint in this pull request. This feature allows users to change their email to receive a fresh verification mail after signup
​
https://linear.app/zuri-project-backend/issue/AUT-31/za-029
​
The previous implementation wasn't working as intended and I just figured out
​
I tested using Postman. I got a fresh temporary email, signed up, copied the token to my Postman headers and made a PATCH request to change email (my endpoint).
I got a success response with a mail sent to my new email. I then tried to log in with the old email and the new email and this worked as intended.
​
- [ x] Bug fix (non-breaking change which fixes an issue)
​
- [ x] My code follows the code style of this project.
- [x ] My change requires a change to the …
> Fix change email endpoint

- controllers/MessagingController/sendWelcomeMail.js
​This is a bug fix for the send welcome email functionality
I reviewed the code base and discovered a spelling error that prevented welcome emails from being sent at first registration
​
​
​
​
​![welcome_email fixed](https://github.com/hngx-org/authentication_service/assets/72075175/26980565-b70a-4f49-8630-b774ead02db6)
​
> fixed a spelling error in send welcome email function

- typescript/config/db.config.ts
- typescript/controllers/AuthController/index.ts
- typescript/controllers/UserController/index.ts
- typescript/controllers/UserController/messaging.ts
- typescript/index.ts
- typescript/models/Permission.ts
- typescript/models/Role.ts
- typescript/models/RolePermission.ts
- typescript/models/User.ts
- typescript/models/UserPermission.ts
- typescript/routes/authRouter.ts
- typescript/services/AuthService/IAuthService.ts
- typescript/services/AuthService/index.ts
- typescript/services/UserService/index.ts
> Added authorize controler in Typescript convert

- controllers/AuthenticationController/createGuest.js
- controllers/AuthenticationController/createUser.js
- controllers/AuthenticationController/login.js
- controllers/MessagingController/sendSignUpEmail.js
- helpers/slugify.js
- middleware/loginResponse.js
- models/Users.js
​
Add a slug field to the DB and implement it in the codebase. This is a request from other teams who need this functionality.
​
​
​A requested feature from another team.
Tested using postman. Querying endpoints and checking the responses.
​
​
​
> add slug to user

- middleware/authGithub.js
- middleware/errorHandlerMiddleware.js
- services/passportService.js
- services/passportServiceFb.js
​updated the oauth signup functions to automatically add slugs to users
this is an example of how users are now being created after importing slugify from the helpers folder
```
user = await User.create({
username: profile.displayName,
first_name: profile.name.givenName,
last_name: profile.name.familyName,
email: profile.emails[0].value,
refresh_token: '',
is_verified: true,
provider: 'google',
slug: await slugify(
profile.name.givenName,
profile.name.familyName,
),
```
i couldnt test this loally since i have no access to the db
​
​
​
​
​
​
> added slugify to social auth user signups

- typescript/middlewares/error.ts
- typescript/utils/index.ts
Refactor responses to include `status` field and not `statusCode`
> refactor responses

- typescript/controllers/UserController/index.ts
- typescript/routes/userRouter.ts
- typescript/services/UserService/IUserService.ts
- typescript/services/UserService/index.ts
​feat: slug added to the signup response
​
​
​
​
​
​
> feat: slug added to the signup

- index.ts
- swagger_output.json
​
swagger documentation initialized
​
documentation
​
To help users access all routes available in the BE
​
​Tested locally
​
​
> Harbephel ts

- utils/index.ts
​
bearer token should be expired in 24 hours
​
​
​bearer token not expiring
​
​
​
- [x ] My code follows the code style of this project.
> bearer token expires in 24 hours

- controllers/UserController/index.ts
- services/Passport/PassportServiceFacebook.ts
- services/Passport/PassportServiceGithub.ts
- services/Passport/PassportServiceGoogle.ts
- services/UserService/index.ts
​
​Create a slug for users registering the app using the oauth methods.
​
​
​
​
​
> add slugify on oauth routes

- controllers/RBACController/index.ts
- routes/rbacRouter.ts
​
​Remove seed endpoints. These endpoints were used during development to automatically seed the DB. It doesn't need to be there in production.
​
​
​
​
​
> remove seed routes

- controllers/UserController/index.ts
- controllers/UserController/messaging.ts
- models/User.ts
- services/UserService/index.ts
- utils/index.ts
​This pr fixed the response gotten from email services
​
​
​
​
​
​
> feat: fixed email service responses

- controllers/UserController/index.ts
- controllers/UserController/validation.ts
- routes/userRouter.ts
- services/UserService/IUserService.ts
- services/UserService/index.ts
​This PR introduces a new feature that creates an endpoint to change the role of any user in the system. The endpoint takes the user ID and the new role as parameters, and updates the database accordingly.
https://linear.app/zuri-portfolio-apprenticeship/issue/AUTH-13/create-an-endpoint-to-change-user-roles​
This feature is required to address the issue of users having inappropriate or outdated roles that do not match their current responsibilities or permissions. 
​
The feature was tested using postman.
​
​
​
> Feat: Change user role functionality

- .env.example
- .eslintrc
- config/db.config.ts
- controllers/AuthController/index.ts
- index.ts
- models/PasswordResetToken.ts
- models/Permission.ts
- models/Role.ts
- models/RolePermission.ts
- models/User.ts
- models/UserPermission.ts
- services/AuthService/index.ts
- services/RoleService/index.ts
- swagger_output.json
- utils/usersRolesPermission.ts
> fix: refactor on auth and role
